global:
  resolve_timeout: 5m

route:
  group_by: ["alertname", "instance"]
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h
  receiver: "telegram"

receivers:
  - name: "telegram"
    telegram_configs:
      - bot_token: "8729682156:AAHiFJAI1FRpcAkOygpA2E-HRjQNZdb0YfQ"
        chat_id: 1046597510
        message: "Alert: {{ .GroupLabels.alertname }} - Firing"
        parse_mode: "HTML"

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "instance"]
